version: '3.7'

services:
    php-apache:
        container_name: advent_of_code
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
